### ISSUE TITLE
Which type of mac?

### ISSUE THREAD

**Issue by rayqusa** [WHCMrShi/Dell-Latitude-3410_Hackintosh#1]
I want to add serial. which type of mac? thank you

**Comment by WHCMrShi** [comment]
I will update this project soon, the latest version will use MacBookPro16,2

**Comment by WHCMrShi** [comment]
I will update this project soon, the latest version will use MacBookPro16,2

**Comment by WHCMrShi** [comment]
Please checkout the latest release, which support for macOS Ventura

**Comment by lifecom** [comment]
MacBookPro16,2 use only Ice Lake CPU's.
Our model use Comet Lake CPU's.
Only iMac20,1 in Apple models lineup use Comet lake CPU's
Perhaps iMac20,1 SMBIOS is more suitable?
