### ISSUE TITLE
DVMT / CFG-Lock

### ISSUE THREAD

**Issue by gatorback** [WHCMrShi/Dell-Latitude-3410_Hackintosh#3]
Did you change DVMT or CFG-lock?  If yes, please think about publishing the details (offsets).

**Comment by WHCMrShi** [comment]
Unlock CFG is not easy for most users, remain locked and use the latest release.  
By the way, you can't simply change DVMT settings in the BIOS of this model.

**Comment by gatorback** [comment]
DVMT was a problem for me, however, it was resolved with modgrubshell: Dell BIOS does not have a UI to change DVMT settings.

**Comment by lifecom** [comment]
[Info about disabling CFG Lock](https://github.com/WHCMrShi/Dell-Latitude-3410_Hackintosh/issues/5).
**NB.** Make sure the BIOS version matches version 1.23.0
