### ISSUE TITLE
Bluetooth not work

### ISSUE THREAD

**Issue by lifecom** [WHCMrShi/Dell-Latitude-3410_Hackintosh#8]
Bluetooth does not work in my laptop with this EFI.
But I found a solution ([source](https://www.reddit.com/r/hackintosh/comments/13lgrrf/comment/jl1nbn3/)):
add to NVRAM>7C436110-AB2A-4BBB-A880-FE41995C9F82
bluetoothInternalControllerInfo 00000000 00000000 00000000 0000
bluetoothExternalDongleFailed 00

May this help someone

**Comment by lifecom** [comment]
I also read on [insanelymac.com](https://www.insanelymac.com/forum/topic/356769-solved-update-to-ventura-134-bluetooth-no-longer-works-bcm94352hmb/page/3/#comment-2806027) - this fork of BlueToolFixup.kext also solves the problem.
It can be download [from latest artifacts of this fork](https://github.com/zxystd/BrcmPatchRAM/actions/runs/5356468997). But I didn't try.

**Comment by mgh457** [comment]
for a short moment, I could activate BT after adding the Data to NVRAM but then it disappeared again.

**Comment by mgh457** [comment]
I managed to get OS13.3.  running with BT. :-)

I changed the ORDER of the Kext with Rel. 2.3 to:

IntelBluetoothIFirmware
IntelBTPatcher
BlueToolFixup
(no other kexts for BT must be used!!!)

Only when disable(deactivating) one BT in OS13.3 I can no activate(enable) ist again :-(
If anybody finds a solution, pls post

**Comment by WHCMrShi** [comment]
I forget to load the IntelBTPatcher.kext added in IntelBluetoothFirmware v2.3.0, sorry for the inconvenience. But I don't use this function much often, so I can't help you with other issues any more:(

Please check the latest release.

**Comment by WHCMrShi** [comment]
Besides, If you are using macOS version before Sonoma, download the latest release of this repository and replace AirportItlwm.kext to corresponding version.

> Versions before Monterey need to replace `BlueToolFixup.kext` by `IntelBluetoothInjector.kext`, and modify config.plist
